/**
 * Firestore repositories (Data Access Layer).
 *
 * Thin, typed wrappers over the modular Firebase client SDK and the typed
 * collection / document helpers in `lib/firebase/converters.ts`. Each repository
 * exposes the smallest surface the Admin_Panel and Project_Viewer need, reading
 * and writing the domain models from `lib/types.ts` without scattering casts.
 *
 * Design notes:
 * - Document ids carry the domain `id` (the converters strip the stored `id`
 *   field on write and merge the document id back on read), so callers always
 *   receive fully-formed domain objects.
 * - Each `Project` document id equals its `Project_ID` (Req 2.2). New ids are
 *   minted by the pure `generateUniqueProjectId` generator, checked for
 *   collisions through `projectRepo.exists` (Req 2.3).
 * - Lead pipeline rules (default `New` status, timeline appends) are owned by
 *   the pure helpers in `lib/leads.ts`; the repository only persists their
 *   results (Req 20.4, 38.2, 38.3).
 * - The repositories use the client SDK and obtain the Firestore handle from
 *   `getClientFirestore()` lazily, so a single instance is reused.
 *
 * Requirements: 2.2, 2.3, 20.2, 33.2, 33.3, 37.1, 37.2, 37.3, 38.2, 38.3
 */

import {
  addDoc,
  deleteDoc,
  doc,
  getDoc,
  getDocs,
  query,
  setDoc,
  updateDoc,
  where,
  writeBatch,
  type DocumentReference,
} from "firebase/firestore";

import { getClientFirestore } from "@/lib/firebase/client";
import {
  leadsCollection,
  plotsCollection,
  projectDoc,
  projectsCollection,
  statusGroupsCollection,
  zonesCollection,
} from "@/lib/firebase/converters";
import { appendNote, appendStatusChange, createLead } from "@/lib/leads";
import { generateUniqueProjectId } from "@/lib/projectId";
import type {
  Lead,
  LeadStatus,
  Plot,
  Project,
  StatusGroup,
  Zone,
} from "@/lib/types";

// ---------------------------------------------------------------------------
// Input shapes
// ---------------------------------------------------------------------------

/**
 * Fields supplied when creating a {@link Project}. The `id` is generated by the
 * repository (Req 2.1) and the `createdAt` / `updatedAt` timestamps are managed
 * on write, so all three are omitted from the caller's input.
 */
export type ProjectInput = Omit<Project, "id" | "createdAt" | "updatedAt">;

/** Fields supplied when creating a {@link Zone}; the id is auto-generated. */
export type ZoneInput = Omit<Zone, "id">;

/** Fields supplied when creating a {@link StatusGroup}; id is auto-generated. */
export type StatusGroupInput = Omit<StatusGroup, "id">;

/**
 * Fields supplied when capturing a new {@link Lead} from an enquiry (Req 20.2).
 * The repository assigns the Firestore document id, defaults the status to
 * `New` and the timeline to empty via {@link createLead} (Req 20.4), and
 * defaults `createdAt` to the current time when omitted.
 */
export type NewLeadData = Omit<Lead, "id" | "status" | "timeline" | "createdAt"> & {
  createdAt?: number;
};

// ---------------------------------------------------------------------------
// Project repository (Req 2.2, 2.3, 33.2)
// ---------------------------------------------------------------------------

export const projectRepo = {
  /**
   * Lists every Project in the projects collection (Req 33.1, 33.2). Used by
   * the Admin_Panel Projects manager to render the inventory of developments.
   */
  async list(): Promise<Project[]> {
    const snapshot = await getDocs(projectsCollection(getClientFirestore()));
    return snapshot.docs.map((d) => d.data());
  },

  /**
   * Loads a Project by id, or `null` when no document exists.
   *
   * @param id The Project_ID (equals the Firestore document id, Req 2.2).
   */
  async get(id: string): Promise<Project | null> {
    const snapshot = await getDoc(projectDoc(getClientFirestore(), id));
    return snapshot.exists() ? snapshot.data() : null;
  },

  /**
   * Reports whether a Project document with the given id already exists. Used
   * as the collision predicate for {@link generateUniqueProjectId} (Req 2.3).
   *
   * @param id Candidate Project_ID.
   * @returns `true` when the id is already taken.
   */
  async exists(id: string): Promise<boolean> {
    const snapshot = await getDoc(projectDoc(getClientFirestore(), id));
    return snapshot.exists();
  },

  /**
   * Creates a Project, minting a unique 5–6 character Project_ID (Req 2.1) that
   * does not collide with any existing project (Req 2.3) and persisting the
   * document under that id (Req 2.2, 33.2). The `createdAt` / `updatedAt`
   * timestamps are stamped to the current time.
   *
   * @param data The project fields (everything except id and timestamps).
   * @returns The generated Project_ID.
   */
  async create(data: ProjectInput): Promise<string> {
    const db = getClientFirestore();
    const id = await generateUniqueProjectId((candidate) => this.exists(candidate));
    const now = Date.now();
    const project: Project = {
      ...data,
      id,
      createdAt: now,
      updatedAt: now,
    };
    await setDoc(projectDoc(db, id), project);
    return id;
  },

  /**
   * Applies a partial update to a Project and refreshes its `updatedAt`
   * timestamp (Req 33.2). The `id` field is never changed.
   *
   * @param id The Project_ID to update.
   * @param patch The fields to change.
   */
  async update(id: string, patch: Partial<Project>): Promise<void> {
    const { id: _ignored, ...rest } = patch;
    void _ignored;
    await updateDoc(projectDoc(getClientFirestore(), id), {
      ...rest,
      updatedAt: Date.now(),
    });
  },

  /**
   * Deletes a Project document (Req 33.2). Destructive; gated to superadmin in
   * the access policy and Security Rules (Req 32.3).
   *
   * @param id The Project_ID to delete.
   */
  async remove(id: string): Promise<void> {
    await deleteDoc(projectDoc(getClientFirestore(), id));
  },
};

// ---------------------------------------------------------------------------
// Plot repository (Req 33.3, 35.1, 37.3)
// ---------------------------------------------------------------------------

export const plotRepo = {
  /**
   * Lists all plots belonging to a project.
   *
   * @param projectId The owning Project_ID.
   */
  async list(projectId: string): Promise<Plot[]> {
    const snapshot = await getDocs(plotsCollection(getClientFirestore(), projectId));
    return snapshot.docs.map((d) => d.data());
  },

  /**
   * Loads a single plot, or `null` when it does not exist.
   *
   * @param projectId The owning Project_ID.
   * @param plotId The plot document id.
   */
  async get(projectId: string, plotId: string): Promise<Plot | null> {
    const ref = doc(plotsCollection(getClientFirestore(), projectId), plotId);
    const snapshot = await getDoc(ref);
    return snapshot.exists() ? snapshot.data() : null;
  },

  /**
   * Creates or updates many plot documents in a single atomic batch, keyed by
   * each plot's `id` (Req 33.3). Used when saving converted GeoJSON to upsert
   * the project's plot inventory (Req 35.1).
   *
   * @param projectId The owning Project_ID.
   * @param plots The plots to write; existing documents are overwritten.
   */
  async upsertMany(projectId: string, plots: Plot[]): Promise<void> {
    const db = getClientFirestore();
    const collectionRef = plotsCollection(db, projectId);
    const batch = writeBatch(db);
    for (const plot of plots) {
      batch.set(doc(collectionRef, plot.id), plot);
    }
    await batch.commit();
  },

  /**
   * Applies a partial update to a single plot (Req 33.3), e.g. changing its
   * status or assigning it to a zone (Req 37.3).
   *
   * @param projectId The owning Project_ID.
   * @param plotId The plot document id.
   * @param patch The fields to change.
   */
  async update(projectId: string, plotId: string, patch: Partial<Plot>): Promise<void> {
    const { id: _ignored, ...rest } = patch;
    void _ignored;
    const ref = doc(plotsCollection(getClientFirestore(), projectId), plotId);
    await updateDoc(ref, rest);
  },
};

// ---------------------------------------------------------------------------
// Zone repository (Req 37.1)
// ---------------------------------------------------------------------------

export const zoneRepo = {
  /** Lists all zones for a project. */
  async list(projectId: string): Promise<Zone[]> {
    const snapshot = await getDocs(zonesCollection(getClientFirestore(), projectId));
    return snapshot.docs.map((d) => d.data());
  },

  /** Loads a single zone, or `null` when it does not exist. */
  async get(projectId: string, zoneId: string): Promise<Zone | null> {
    const ref = doc(zonesCollection(getClientFirestore(), projectId), zoneId);
    const snapshot = await getDoc(ref);
    return snapshot.exists() ? snapshot.data() : null;
  },

  /**
   * Creates a zone with an auto-generated id and persists it (Req 37.1).
   *
   * @param data The zone fields (everything except id).
   * @returns The generated zone id.
   */
  async create(data: ZoneInput): Promise<string> {
    const collectionRef = zonesCollection(getClientFirestore(), data.projectId);
    const ref = await addDoc(collectionRef, { ...data, id: "" } as Zone);
    return ref.id;
  },

  /** Applies a partial update to a zone (Req 37.1). */
  async update(projectId: string, zoneId: string, patch: Partial<Zone>): Promise<void> {
    const { id: _ignored, ...rest } = patch;
    void _ignored;
    const ref = doc(zonesCollection(getClientFirestore(), projectId), zoneId);
    await updateDoc(ref, rest);
  },

  /** Deletes a zone (Req 37.1). */
  async remove(projectId: string, zoneId: string): Promise<void> {
    const ref = doc(zonesCollection(getClientFirestore(), projectId), zoneId);
    await deleteDoc(ref);
  },
};

// ---------------------------------------------------------------------------
// Status group repository (Req 37.2)
// ---------------------------------------------------------------------------

export const statusGroupRepo = {
  /** Lists all status groups for a project. */
  async list(projectId: string): Promise<StatusGroup[]> {
    const snapshot = await getDocs(
      statusGroupsCollection(getClientFirestore(), projectId),
    );
    return snapshot.docs.map((d) => d.data());
  },

  /** Loads a single status group, or `null` when it does not exist. */
  async get(projectId: string, groupId: string): Promise<StatusGroup | null> {
    const ref = doc(statusGroupsCollection(getClientFirestore(), projectId), groupId);
    const snapshot = await getDoc(ref);
    return snapshot.exists() ? snapshot.data() : null;
  },

  /**
   * Creates a status group with an auto-generated id and persists it
   * (Req 37.2).
   *
   * @param data The status-group fields (everything except id).
   * @returns The generated status-group id.
   */
  async create(data: StatusGroupInput): Promise<string> {
    const collectionRef = statusGroupsCollection(getClientFirestore(), data.projectId);
    const ref = await addDoc(collectionRef, { ...data, id: "" } as StatusGroup);
    return ref.id;
  },

  /** Applies a partial update to a status group (Req 37.2). */
  async update(
    projectId: string,
    groupId: string,
    patch: Partial<StatusGroup>,
  ): Promise<void> {
    const { id: _ignored, ...rest } = patch;
    void _ignored;
    const ref = doc(statusGroupsCollection(getClientFirestore(), projectId), groupId);
    await updateDoc(ref, rest);
  },

  /** Deletes a status group (Req 37.2). */
  async remove(projectId: string, groupId: string): Promise<void> {
    const ref = doc(statusGroupsCollection(getClientFirestore(), projectId), groupId);
    await deleteDoc(ref);
  },
};

// ---------------------------------------------------------------------------
// Lead repository (Req 20.2, 38.2, 38.3)
// ---------------------------------------------------------------------------

export const leadRepo = {
  /**
   * Captures a new Lead from an enquiry, referencing the Project and Plot
   * (Req 20.2). The status is defaulted to `New` and the timeline to empty via
   * {@link createLead} (Req 20.4), and the Firestore document id is generated
   * on write.
   *
   * @param data The enquiry fields (project, plot, contact details, message).
   * @returns The generated lead document id.
   */
  async create(data: NewLeadData): Promise<string> {
    const lead = createLead({
      ...data,
      id: "",
      createdAt: data.createdAt ?? Date.now(),
    });
    const ref = await addDoc(leadsCollection(getClientFirestore()), lead);
    return ref.id;
  },

  /**
   * Lists leads, optionally restricted to a single project (Req 38.1). When
   * `projectId` is supplied the query filters on the stored `projectId` field.
   *
   * @param projectId Optional Project_ID to scope the leads to.
   */
  async list(projectId?: string): Promise<Lead[]> {
    const collectionRef = leadsCollection(getClientFirestore());
    const snapshot = await getDocs(
      projectId === undefined
        ? collectionRef
        : query(collectionRef, where("projectId", "==", projectId)),
    );
    return snapshot.docs.map((d) => d.data());
  },

  /**
   * Applies a partial update to a lead (Req 38.1). The `id` field is never
   * changed. To record a status transition in the timeline, prefer
   * {@link leadRepo.changeStatus}; to add a note, use {@link leadRepo.addNote}.
   *
   * @param id The lead document id.
   * @param patch The fields to change.
   */
  async update(id: string, patch: Partial<Lead>): Promise<void> {
    const { id: _ignored, ...rest } = patch;
    void _ignored;
    await updateDoc(leadDoc(id), rest);
  },

  /**
   * Changes a lead's pipeline status and records the transition as a single
   * `status_change` timeline entry via {@link appendStatusChange} (Req 38.2,
   * 38.3). The lead is read, transitioned in memory, then its `status` and
   * `timeline` are persisted.
   *
   * @param id The lead document id.
   * @param toStatus The status to move the lead to.
   * @param by Optional identifier of the actor performing the change.
   * @returns The updated Lead.
   * @throws {Error} When no lead with the given id exists.
   */
  async changeStatus(id: string, toStatus: LeadStatus, by?: string): Promise<Lead> {
    const ref = leadDoc(id);
    const snapshot = await getDoc(ref);
    if (!snapshot.exists()) {
      throw new Error(`Lead not found: ${id}`);
    }
    const updated = appendStatusChange(snapshot.data(), toStatus, by);
    await updateDoc(ref, { status: updated.status, timeline: updated.timeline });
    return updated;
  },

  /**
   * Adds a note to a lead and records it as a single `note` timeline entry via
   * {@link appendNote} (Req 38.3). The lead is read, annotated in memory, then
   * its `timeline` is persisted.
   *
   * @param id The lead document id.
   * @param note The note text to record.
   * @param by Optional identifier of the actor adding the note.
   * @returns The updated Lead.
   * @throws {Error} When no lead with the given id exists.
   */
  async addNote(id: string, note: string, by?: string): Promise<Lead> {
    const ref = leadDoc(id);
    const snapshot = await getDoc(ref);
    if (!snapshot.exists()) {
      throw new Error(`Lead not found: ${id}`);
    }
    const updated = appendNote(snapshot.data(), note, by);
    await updateDoc(ref, { timeline: updated.timeline });
    return updated;
  },
};

/** Builds a typed reference to a lead document in the top-level collection. */
function leadDoc(id: string): DocumentReference<Lead> {
  return doc(leadsCollection(getClientFirestore()), id);
}
